var target_words = [
    "Python",
    "hadoop",
    "SQL", "mySQL", "noSQL",
    "javascript",
    "html",
    "css",
    "mongodb",
    "php",
    "d3",
    "leaflet",
    "tableau",
    "api",
    "js",
    "algorithms",
    "bootstrap",
    "git", 
    "gitHub",
    "excel"
]